repos:
  # Common hooks for various checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace  # Removes trailing whitespace from files
      - id: end-of-file-fixer    # Ensures a newline at the end of each file
        exclude: ^data/.*        # Exclude files in the data directory
      - id: check-yaml           # Validates YAML files syntax
      - id: detect-private-key   # Searches for private keys in the repository
  # Code formatting for jupyter notebooks with Black Jupyter
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
      - id: black-jupyter
